"""Update_Food_and_Recommendation_models_for_new_dataset

Revision ID: 04230d881717
Revises: 1e33cd668004
Create Date: 2025-05-25 22:58:32.896782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04230d881717'
down_revision = '1e33cd668004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet_goals', schema=None) as batch_op:
        batch_op.alter_column('medical_condition',
               existing_type=mysql.ENUM('none', 'diabetes', 'hypertension', 'obesity'),
               nullable=False,
               existing_server_default=sa.text("'none'"))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'completed', 'abandoned'),
               nullable=False,
               existing_server_default=sa.text("'active'"))

    with op.batch_alter_table('food_preferences', schema=None) as batch_op:
        batch_op.alter_column('preference_type',
               existing_type=mysql.ENUM('vegetarian', 'halal', 'dairy_free', 'nut_free', 'seafood_free', 'egg_free', 'soy_free'),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_kj', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dietary_fiber', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pufa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cholesterol', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_e', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_b1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_b2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_b6', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_folic_acid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_c', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sodium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('potassium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calcium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('magnesium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phosphorus', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('iron', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('zinc', sa.Float(), nullable=True))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('meal_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('food_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('meal_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('zinc')
        batch_op.drop_column('iron')
        batch_op.drop_column('phosphorus')
        batch_op.drop_column('magnesium')
        batch_op.drop_column('calcium')
        batch_op.drop_column('potassium')
        batch_op.drop_column('sodium')
        batch_op.drop_column('vitamin_c')
        batch_op.drop_column('total_folic_acid')
        batch_op.drop_column('vitamin_b6')
        batch_op.drop_column('vitamin_b2')
        batch_op.drop_column('vitamin_b1')
        batch_op.drop_column('vitamin_e')
        batch_op.drop_column('vitamin_a')
        batch_op.drop_column('cholesterol')
        batch_op.drop_column('pufa')
        batch_op.drop_column('dietary_fiber')
        batch_op.drop_column('energy_kj')

    with op.batch_alter_table('food_preferences', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('preference_type',
               existing_type=mysql.ENUM('vegetarian', 'halal', 'dairy_free', 'nut_free', 'seafood_free', 'egg_free', 'soy_free'),
               nullable=True)

    with op.batch_alter_table('diet_goals', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'completed', 'abandoned'),
               nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('medical_condition',
               existing_type=mysql.ENUM('none', 'diabetes', 'hypertension', 'obesity'),
               nullable=True,
               existing_server_default=sa.text("'none'"))

    # ### end Alembic commands ###
