"""Add food_status and meal_type to recommendations

Revision ID: 1e33cd668004
Revises: 759e3c8dd00d
Create Date: 2025-05-10 20:35:42.095489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e33cd668004'
down_revision = '759e3c8dd00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet_goals', schema=None) as batch_op:
        batch_op.alter_column('medical_condition',
               existing_type=mysql.ENUM('none', 'diabetes', 'hypertension', 'obesity'),
               nullable=True,
               existing_server_default=sa.text("'none'"))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'completed', 'abandoned'),
               nullable=True,
               existing_server_default=sa.text("'active'"))

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('meal_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_column('meal_type')
        batch_op.drop_column('food_status')

    with op.batch_alter_table('diet_goals', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'completed', 'abandoned'),
               nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('medical_condition',
               existing_type=mysql.ENUM('none', 'diabetes', 'hypertension', 'obesity'),
               nullable=False,
               existing_server_default=sa.text("'none'"))

    # ### end Alembic commands ###
