"""add_food_preference_fields

Revision ID: b6b5ca62c2d5
Revises: b4155a23d06b
Create Date: 2025-02-26 23:01:17.361518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b5ca62c2d5'
down_revision = 'b4155a23d06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_kosher', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contains_eggs', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('contains_eggs')
        batch_op.drop_column('is_kosher')

    # ### end Alembic commands ###
