"""Update recommendation models for workflow

Revision ID: fa86303018df
Revises: cf02c1a05e57
Create Date: 2025-02-26 17:53:06.302787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa86303018df'
down_revision = 'cf02c1a05e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preference_type', sa.Enum('vegetarian', 'halal', 'kosher', 'peanut_free', 'seafood_free', 'dairy_free'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diet_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('goal_type',
               existing_type=mysql.ENUM('weight_loss', 'muscle_gain', 'maintenance', 'diabetes_friendly'),
               nullable=False)
        batch_op.alter_column('target_weight',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('target_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('food_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('recommendation_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('meal_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_type', mysql.ENUM('breakfast', 'lunch', 'dinner', 'snack'), nullable=True))
        batch_op.alter_column('recommendation_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('food_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('feedback_date')

    with op.batch_alter_table('diet_goals', schema=None) as batch_op:
        batch_op.alter_column('target_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('target_weight',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('goal_type',
               existing_type=mysql.ENUM('weight_loss', 'muscle_gain', 'maintenance', 'diabetes_friendly'),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('updated_at')

    op.drop_table('food_preferences')
    # ### end Alembic commands ###
