"""Add food preference fields

Revision ID: ff1aeb46d7dd
Revises: fa86303018df
Create Date: 2025-02-26 18:18:46.950066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1aeb46d7dd'
down_revision = 'fa86303018df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vegetarian', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_halal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contains_peanuts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contains_seafood', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contains_dairy', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('contains_dairy')
        batch_op.drop_column('contains_seafood')
        batch_op.drop_column('contains_peanuts')
        batch_op.drop_column('is_halal')
        batch_op.drop_column('is_vegetarian')

    # ### end Alembic commands ###
